# Generated by Django 4.1 on 2023-11-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='your_additional_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
