# Generated by Django 4.1 on 2023-11-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_customuser_your_additional_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='your_additional_field',
        ),
    ]
