# Generated by Django 4.1 on 2023-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_nasaevent_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nasaevent',
            name='event_id',
            field=models.CharField(max_length=50),
        ),
    ]
