# Generated by Django 4.1 on 2024-09-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='tip',
            old_name='author',
            new_name='category',
        ),
    ]
