name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PA_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        ssh ${{ secrets.PA_USERNAME }}@ssh.pythonanywhere.com << 'EOF'
        source /home/${{ secrets.PA_USERNAME }}/SpaceCodey/venv/bin/activate
        cd /home/${{ secrets.PA_USERNAME }}/SpaceCodey/SpaceCodey
        git pull origin
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        EOF

    - name: Reload PythonAnywhere Web App
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_DOMAIN_NAME: <your_custom_domain>
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${{ env.PA_USERNAME }}/webapps/${{ env.PA_DOMAIN_NAME }}/reload/ \
             -H "Authorization: Token ${{ env.PA_API_TOKEN }}"
