name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@ssh.pythonanywhere.com << EOF
        cd SpaceCodey/SpaceCodey/
        git pull origin production
        source ../venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        EOF

    - name: Reload PythonAnywhere Web App
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.SSH_USER }}
        PA_DOMAIN_NAME: ${{ secrets.PA_DOMAIN_NAME }}
      run: |
        curl -X POST https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_DOMAIN_NAME}/reload/ \
             -H "Authorization: Token ${PA_API_TOKEN}"
