name: Build and Deploy to PythonAnywhere

on:
  push:
    branches:
      - production  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Archive build
      run: |
        tar -czf build.tar.gz .
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
          name: build-artifact
          path: build.tar.gz

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - name: Extract build artifact
      run: |
        tar -xzf build.tar.gz

    - name: Deploy to PythonAnywhere via SSH
      env:
        SSH_HOST: ssh.pythonanywhere.com
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        echo "Deploying to PythonAnywhere..."
        expect <<EOF
        set timeout -1
        spawn ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST
        expect "password:"
        send "$SSH_PASSWORD\r"
        expect "$ "
        send "cd SpaceCodey/SpaceCodey/\r"
        send "git pull origin production\r"
        send "source ../venv/bin/activate\r"
        send "pip install -r requirements.txt\r"
        send "python manage.py migrate\r"
        send "python manage.py collectstatic --noinput\r"
        send "exit\r"
        expect eof
        EOF
