name: Build and deploy Python app to Azure Web App - SpaceCodey

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Create and start virtual environment
      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 5: Collect static files (use the correct path to manage.py)
      - name: Collect static files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      # Step 6: Apply database migrations
      - name: Run migrations
        run: |
          source venv/bin/activate
          python manage.py migrate

      # Step 7: Zip the deployment files
      - name: Zip artifact for deployment
        run: zip release.zip SpaceCodey -r


      # Step 8: Upload the artifact for deployment jobs
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Step 9: Download the built artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Step 10: Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Step 11: Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_48131F1CA9854590AE193AC185D8B050 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BFE9ACDF356E450C8418ED692B18C051 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B2194B7E3E944DDBB80A46B31BC9B6D9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
            app-name: 'SpaceCodey'
            slot-name: 'Production'
            target-path: '/home/site/wwwroot'  
        
